name: Mirroring

on: [] #[push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: ${{ secrets.GIT_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USER }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          GIT_PUSH_ARGS: --push-option=ci.skip --tags --force --prune
      - uses: nelonoel/branch-name@v1.0.1
      - name: Trigger GitLab Pipeline
        run: |
          sudo apt install jq
          result=$(curl -X POST -F token=${{ secrets.PNNL_PIPELINE_TRIGGER_TOKEN }} -F ref=${BRANCH_NAME} https://gitlab.pnnl.gov/api/v4/projects/1056/trigger/pipeline)
          exit_code=$?
          pipeline_id=$(echo $result | jq '.id')
          echo "PIPELINE_ID=${pipeline_id}" >> $GITHUB_ENV
          exit $exit_code
